CREATE DATABASE IF NOT EXISTS agrishield_db;

USE agrishield_db;

DROP TABLE IF EXISTS fields;

CREATE TABLE fields (
    id INT AUTO_INCREMENT PRIMARY KEY,
    farmer_name VARCHAR(100) NOT NULL DEFAULT 'Aman Kumar',
    name VARCHAR(100) NOT NULL,
    location VARCHAR(255) NOT NULL,
    latitude DECIMAL(9, 6) NOT NULL DEFAULT 25.435800,
    longitude DECIMAL(9, 6) NOT NULL DEFAULT 81.846300,
    crop VARCHAR(100) NOT NULL,
    area_acres DECIMAL(10, 2) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);